baseURL = '/'
languageCode = 'en-us'
title = 'Semla'
theme = 'semla'

[markup.goldmark.renderer]
unsafe= true

copyright = 'Everything is mine'
defaultContentLanguage = 'en'
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    title = 'Semla AI'
    weight = 1
    [languages.en.params]
      linkedin = 'https://linkedin.com/whoever'
  [languages.ar]
    contentDir = 'content/ar'
    languageName = 'Arabic'
    languagedirection = 'rtl'
    title = 'مدونتي'
    weight = 2

[params]
  [params.navigation]
    help = 'Help'