baseURL = 'https://semla.ai/'
defaultContentLanguage = "en"
languageCode = 'en-us'
title = 'Semla AI'
description = 'SEMLA - Software Engineering for Machine Learning Applications'
theme = 'semla'

[markup.goldmark.renderer]
unsafe= true
