[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
title = "Semla AI - Elevate with Data"
weight = 1


[ar]
languageName = "العربية"
languageCode = "ar"
contentDir = "content/ar"
languagedirection = "rtl"
title = "Semla AI - سملا للذكاء الاصطناعي - حلّق بالبيانات"
weight = 2
