[[main]]
name = "الصفحة الرئيسية"
url = "/"
weight = 10

[[main]]
name = "الخدمات"
url = "/#services"
weight = 20

[[main]]
name = "المجالات"
url = "/#domains"
weight = 30

[[main]]
name = "منتجات"
url = "/#products"
weight = 40

[[main]]
name = "مدونة"
url = "/blog/"
weight = 50

[[main]]
name = "من نحن"
url = "/#about"
weight = 60
