logo = '/img/logo.png'


########################### contact info ############################

phone = "000 00 00 00"
email = "info@semla.ai"


########################### social icons ############################

[[social]]
name = "Facebook"
icon = "fa-brands fa-facebook-f fa-xl"
link = "https://www.facebook.com/"

[[social]]
name = "Twitter"
icon = "fa-brands fa-twitter fa-xl"
link = "https://twitter.com/semla_ai"

[[social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin-in fa-xl"
link = "https://www.linkedin.com/company/semla-ai"

[[social]]
name = "YouTube"
icon = "fa-brands fa-youtube fa-xl"
link = "https://www.youtube.com/"
