logo = '/img/logo.png'


########################### contact info ############################

phone = "000 00 00 00"
email = "email@gmail.com"


########################### social icons ############################

[[social]]
name = "Twitter"
icon = "fa-brands fa-twitter fa-xl"
link = "https://twitter.com/"

[[social]]
name = "GitHub"
icon = "fa-brands fa-github fa-xl"
link = "https://github.com/"

[[social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-xl"
link = "https://linkedin.com/"

[[social]]
name = "YouTube"
icon = "fa-brands fa-youtube fa-xl"
link = "https://www.youtube.com/"

